name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install Ruby Dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Build the Jekyll Website
      run: bundle exec jekyll build

    - name: Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.9.0
      with:
        branch: gh-pages
        folder: _site/
