name: Test Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  jekyll:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install Ruby Dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.10'
        bundler-cache: true

    - name: Try to build the Jekyll Website
      run: bundle exec jekyll build --drafts --unpublished --future
